# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD shopDEV

on:
  push:
    branches: [ "master" ]
jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Create .env file
      run: |
        echo "DEV_APP_PORT=${{ secrets.DEV_APP_PORT }}" >> .env
        echo "DEV_DB_HOST=${{ secrets.DEV_DB_HOST }}" >> .env
        echo "DEV_DB_PORT=${{ secrets.DEV_DB_PORT }}" >> .env
        echo "DEV_DB_NAME=${{ secrets.DEV_DB_NAME }}" >> .env
        echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" >> .env
        echo "DISCORD_CHANNEL_ID=${{ secrets.DISCORD_CHANNEL_ID }}" >> .env

    - name: Debug .env file (optional)
      run: |
        grep -v 'DISCORD_TOKEN' .env | grep -v 'DISCORD_CHANNEL_ID'
        
    - run: npm ci
    - run: pm2 restart shopdev-backend
